objects/Billing__c.object
<CustomObject>
    <description>Contains data about guest&apos;s expenses</description>
    <label>Billing</label>
    <nameField>
        <label>Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reservation__c.object
<CustomObject>
    <description>Contains data about reservations made by clients (Guest) on a hotel room (Room)</description>
    <fields>
        <fullName>Billing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing</label>
        <referenceTo>Billing__c</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <displayFormat>Res-{0000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service__c.object
<CustomObject>
    <description>Contains a data about services available in the hotel</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Additional informations on the service</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Billing__c.object
<CustomObject>
    <fields>
        <fullName>Billing__c</fullName>
        <label>Billing</label>
        <referenceTo>Billing__c</referenceTo>
        <relationshipLabel>Services-Billings</relationshipLabel>
        <relationshipName>Services_Billings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Services-Billings</relationshipLabel>
        <relationshipName>Services_Billings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service-Billing</label>
    <nameField>
        <label>Service-Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services-Billings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ShowBillingDataController.cls
public with sharing class ShowBillingDataController {

    @AuraEnabled
    public static List<Service_Billing__c> getBillings(Id reservationId){
        Id billingId = getBillingByReservationId(reservationId);
        System.debug('billingId : ' + billingId);
        return [SELECT Name, Service__r.Name, Service__r.Price__c, Service__r.Description__c FROM Service_Billing__c WHERE Billing__c = :billingId];
    }

    public static Id getBillingByReservationId(Id reservationId){
        List<Reservation__c> billing = [SELECT Billing__r.Id FROM Reservation__c WHERE Reservation__c.Id = :reservationId];
        return billing[0].Billing__r.Id;
    }
}