objects/Billing__c.object
<CustomObject>
    <description>Contains data about guest&apos;s expenses</description>
    <label>Billing</label>
    <nameField>
        <label>Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reservation__c.object
<CustomObject>
    <description>Contains data about reservations made by clients (Guest) on a hotel room (Room)</description>
    <fields>
        <fullName>Billing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing</label>
        <referenceTo>Billing__c</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <displayFormat>Res-{0000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service__c.object
<CustomObject>
    <description>Contains a data about services available in the hotel</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Billing__c.object
<CustomObject>
    <fields>
        <fullName>Billing__c</fullName>
        <label>Billing</label>
        <referenceTo>Billing__c</referenceTo>
        <relationshipLabel>Services-Billings</relationshipLabel>
        <relationshipName>Services_Billings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Services-Billings</relationshipLabel>
        <relationshipName>Services_Billings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service-Billing</label>
    <nameField>
        <label>Service-Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services-Billings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserMenuHotelServicesController.cls
public with sharing class UserMenuHotelServicesController {
    @AuraEnabled
    public static Service_Billing__c addBilling(ID reservationId, Service__c service){
        Id billingId = getBillingByReservationId(reservationId);

        Service_Billing__c newServiceBilling = new Service_Billing__c(
            Name = service.Name,
            Service__c = service.Id,
            Billing__c = billingId
        );
    
        insert newServiceBilling;
        System.debug('newServiceBilling inserted');
        return newServiceBilling;
    }

    private static Id getBillingByReservationId(Id reservationId){
        List<Reservation__c> billing = [SELECT Billing__r.Id FROM Reservation__c WHERE Reservation__c.Id = :reservationId];
        return billing[0].Billing__r.Id;
    }
}