objects/Guest__c.object
<CustomObject>
    <description>Object containing data about the hotel&apos;s clients</description>
    <label>Guest</label>
    <nameField>
        <displayFormat>Guest-{0000}</displayFormat>
        <label>Guest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reservation__c.object
<CustomObject>
    <description>Contains data about reservations made by clients (Guest) on a hotel room (Room)</description>
    <fields>
        <fullName>Check_In__c</fullName>
        <description>Date when a guest wants to check in</description>
        <label>Check In</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Out__c</fullName>
        <description>Date when guest wants to check out</description>
        <label>Check Out</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has a guest confirm his stay in the hotel?</description>
        <label>Confirmed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Guest__c</fullName>
        <description>Links to a guest who had made the booking</description>
        <label>Guest</label>
        <referenceTo>Guest__c</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <description>Room to which reservation is made</description>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <displayFormat>Res-{0000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <description>Contains data about rooms available in hotel</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SummaryPopupController.cls
public with sharing class SummaryPopupController {
    @AuraEnabled
    public static Reservation__c createReservation(Guest__c guest, Room__c room, Date checkIn, Date checkOut, Decimal totalPrice){
        Reservation__c reservation = new Reservation__c(
        Check_In__c = checkIn,
        Check_Out__c = checkOut,
        Confirmed__c = true,
        Guest__c = guest.Id,
        Room__c = room.Id
        );

        insert reservation;
        updateCharge(guest, totalPrice);
        return reservation;
    }

    private static void updateCharge(Guest__c guest, Decimal amount) {
        Guest__c guestToUpdate = [SELECT Charge__c FROM Guest__c WHERE Id = :guest.Id];
        guestToUpdate.Charge__c = guestToUpdate.Charge__c + amount;

        update guestToUpdate;
    }
}