objects/Guest__c.object
<CustomObject>
    <description>Object containing data about the hotel&apos;s clients</description>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Guest</label>
    <nameField>
        <displayFormat>Guest-{0000}</displayFormat>
        <label>Guest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Hotel__c.object
<CustomObject>
    <description>Contains a hotel object and its data</description>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address to the hotel containing street name and number. For the city refer to &apos;City&apos; field</description>
        <label>Address</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Contains the city name where hotel is located</description>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Contains an email address of the hotel</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Contains a data about hotel&apos;s rating (1-5 stars)</description>
        <label>Rating</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reservation__c.object
<CustomObject>
    <description>Contains data about reservations made by clients (Guest) on a hotel room (Room)</description>
    <fields>
        <fullName>Check_In__c</fullName>
        <description>Date when a guest wants to check in</description>
        <label>Check In</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Out__c</fullName>
        <description>Date when guest wants to check out</description>
        <label>Check Out</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guest__c</fullName>
        <description>Links to a guest who had made the booking</description>
        <label>Guest</label>
        <referenceTo>Guest__c</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <description>Room to which reservation is made</description>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <displayFormat>Res-{0000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <description>Contains data about rooms available in hotel</description>
    <fields>
        <fullName>Double_Beds__c</fullName>
        <label>Double Beds</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Executive_Room__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this room an executive one</description>
        <label>Executive Room?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <description>Refers which hotel owns the room</description>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price_for_Night__c</fullName>
        <description>Price PER ONE PERSON</description>
        <label>Price for Night</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Single_Beds__c</fullName>
        <label>Single Beds</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service__c.object
<CustomObject>
    <description>Contains a data about services available in the hotel</description>
    <fields>
        <fullName>Hotel__c</fullName>
        <description>Refers to which hotel this service is available in</description>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserMenuControllerTest.cls
@isTest
private class UserMenuControllerTest {
    @isTest static void getReservationsTest() {
        // INSERT HOTEL
        Hotel__c newHotel = new Hotel__c(
            Name = 'Hotel Test', 
            Address__c = 'Testowa 1',
            City__c = 'Testowo',
            Rating__c = 2
        );
        insert newHotel;

        // INSERT ROOMS
        Room__c newRoom = new Room__c(
            Name = 'Room 1',
            Hotel__c = newHotel.Id,
            Single_Beds__c = 2,
            Double_Beds__c = 2,
            Price_for_Night__c = 50,
            Executive_Room__c = false
        );
        insert newRoom;
        
        // INSERT GUEST AND RESERVATION
        Guest__c newGuest = new Guest__c(
            First_Name__c = 'Peter',
            Last_Name__c = 'Alloy',
            Email__c = 'testcase@test.com'
        );
        insert newGuest;

        Reservation__c newReservation = new Reservation__c(
            Check_In__c	= Date.newInstance(2019,7,4),
            Check_Out__c = Date.newInstance(2019,7,7),
            Guest__c = newGuest.Id,
            Room__c	= newRoom.Id
        );
        insert newReservation;
        
        Test.startTest();
        
        List<Reservation__c> reservations = UserMenuController.getReservations(newGuest.Id);
        
        Test.stopTest();
        
        System.assertEquals(1, reservations.size());
    }
    
    @isTest static void getServicesTest() {
                // INSERT HOTEL
        Hotel__c newHotel = new Hotel__c(
            Name = 'Hotel Test', 
            Address__c = 'Testowa 1',
            City__c = 'Testowo',
            Rating__c = 2
        );
        insert newHotel;

        // INSERT ROOMS
        Room__c newRoom = new Room__c(
            Name = 'Room 1',
            Hotel__c = newHotel.Id,
            Single_Beds__c = 2,
            Double_Beds__c = 2,
            Price_for_Night__c = 50,
            Executive_Room__c = false
        );
        insert newRoom;
        
        // INSERT GUEST AND RESERVATION
        Guest__c newGuest = new Guest__c(
            First_Name__c = 'Peter',
            Last_Name__c = 'Alloy',
            Email__c = 'testcase@test.com'
        );
        insert newGuest;

        Reservation__c newReservation = new Reservation__c(
            Check_In__c	= Date.newInstance(2019,7,4),
            Check_Out__c = Date.newInstance(2019,7,7),
            Guest__c = newGuest.Id,
            Room__c	= newRoom.Id
        );
        insert newReservation;
        
        // INSERT SERVICES TO HOTEL
        Service__c newService = new Service__c(
        	Name = 'Test service',
            Hotel__c = newHotel.Id,
            Price__c = 20
        );
        insert newService;
        
        Test.startTest();
        
        List<Service__c> services = UserMenuController.getServices(newReservation.Id);
        
        Test.stopTest();
        
        System.assertEquals(1, services.size());
    }
    
    @isTest static void updateChargeTest() {
        // TBA
    }
}