objects/Guest__c.object
<CustomObject>
    <description>Object containing data about the hotel&apos;s clients</description>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Guest</label>
    <nameField>
        <displayFormat>Guest-{0000}</displayFormat>
        <label>Guest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ChangeUserDataModalControllerTest.cls
@isTest
private class ChangeUserDataModalControllerTest {
    @testSetup static void setup() {
        Guest__c newGuest = new Guest__c(
            First_Name__c = 'Peter', 
            Last_Name__c = 'Alloy', 
            Email__c = 'testcase@test.com'
        );
        
        insert newGuest;
    }

    @isTest static void updateGuestTest() {
        Guest__c newGuest = [SELECT First_Name__c FROM Guest__c LIMIT 1];
        String guestId = newGuest.Id;
        
        Guest__c theGuest = [SELECT First_Name__c FROM Guest__c WHERE Id = :guestId LIMIT 1];
        String oldName = theGuest.First_Name__c;

        Test.startTest();

        theGuest.First_Name__c = 'Alex';
        ChangeUserDataModalController.updateGuest(theGuest);

        theGuest = [SELECT First_Name__c FROM Guest__c WHERE Id = :guestId LIMIT 1];
        String newName = theGuest.First_Name__c;
        Test.stopTest();

        System.assertEquals('Peter', oldName);
        System.assertEquals('Alex', newName);
    }
}