objects/Guest__c.object
<CustomObject>
    <description>Object containing data about the hotel&apos;s clients</description>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Guest</label>
    <nameField>
        <displayFormat>Guest-{0000}</displayFormat>
        <label>Guest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GuestBookingController.cls
public class GuestBookingController {
     @AuraEnabled
     public static Guest__c createGuest(Guest__c guest) {
         Guest__c newGuest = new Guest__c();
         newGuest.First_Name__c = guest.First_Name__c;
         newGuest.Last_Name__c = guest.Last_Name__c;
         newGuest.Phone__c = guest.Phone__c;
         newGuest.Charge__c = guest.Charge__c;
         newGuest.Email__c = guest.Email__c;
         insert newGuest;
         System.debug('Inside createGuest method: guest Id -' + newGuest.Id);
         return newGuest;
     }

     @AuraEnabled
     public static Guest__c findEmail(String email){
         return [SELECT Name, Charge__c, First_Name__c, Last_Name__c, Email__c, Phone__c FROM Guest__c WHERE Email__c = :email];
     }
}