objects/Hotel__c.object
<CustomObject>
    <description>Contains a hotel object and its data</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <description>Contains data about rooms available in hotel</description>
    <fields>
        <fullName>Double_Beds__c</fullName>
        <label>Double Beds</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <description>Refers which hotel owns the room</description>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Maximum_People_in_the_Room__c</fullName>
        <formula>Single_Beds__c  + (2 *  Double_Beds__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Maximum People in the Room</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_for_Night__c</fullName>
        <description>Price PER ONE PERSON</description>
        <label>Price for Night</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Single_Beds__c</fullName>
        <label>Single Beds</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SearchHotelsController.cls
public with sharing class SearchHotelsController {
    @AuraEnabled
    public static List<Hotel__c> getHotels() {
        // Perform isAccessible() checking first, then
        return [SELECT Id, Name 
                FROM Hotel__c];
    }

    @AuraEnabled
    public static List<Room__c> getRooms(Id id) {
        // Perform isAccessible() checking first, then
        return [SELECT Name, Single_Beds__c, Double_Beds__c, Price_for_Night__c, Maximum_People_in_the_Room__c
                FROM Room__c WHERE Id = :id];
    }
}