objects/Hotel__c.object
<CustomObject>
    <description>Contains a hotel object and its data</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Reservation__c.object
<CustomObject>
    <description>Contains data about reservations made by clients (Guest) on a hotel room (Room)</description>
    <fields>
        <fullName>Room__c</fullName>
        <description>Room to which reservation is made</description>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <displayFormat>Res-{0000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <description>Contains data about rooms available in hotel</description>
    <fields>
        <fullName>Hotel__c</fullName>
        <description>Refers which hotel owns the room</description>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service__c.object
<CustomObject>
    <description>Contains a data about services available in the hotel</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Additional informations on the service</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <description>Refers to which hotel this service is available in</description>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UserMenuReservationsController.cls
public with sharing class UserMenuReservationsController {
   @AuraEnabled
    public static List<Service__c> getServices(Id reservationId){
        Id hotelId = getHotelId(reservationId);
        List<Service__c> services = [SELECT Name, Price__c, Description__c FROM Service__c WHERE Hotel__c = :hotelId];
        
        if (services.size() > 0){
          return services;
        }
        return null;
    }

    private static Id getHotelId(Id reservationId){
        List<Reservation__c> hotel = [SELECT Room__r.Hotel__c FROM Reservation__c WHERE Id = :reservationId LIMIT 1];
        return hotel.get(0).Room__r.Hotel__c;
    }
}