objects/Hotel__c.object
<CustomObject>
    <description>Contains a hotel object and its data</description>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address to the hotel containing street name and number. For the city refer to &apos;City&apos; field</description>
        <label>Address</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Contains the city name where hotel is located</description>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Contains a data about hotel&apos;s rating (1-5 stars)</description>
        <label>Rating</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HotelDropdownListControllerTest.cls
@isTest
private class HotelDropdownListControllerTest {
    @testSetup static void setup() {
        List<Hotel__c> hotels = new List<Hotel__c>();

        Hotel__c newHotel = new Hotel__c(
            Name = 'Hotel Test', 
            Address__c = 'Testowa 1',
            City__c = 'Testowo',
            Rating__c = 2
        );
        hotels.add(newHotel);

        newHotel = new Hotel__c(
            Name = 'Hotel Test 2', 
            Address__c = 'Testowa 2',
            City__c = 'Testowo',
            Rating__c = 1
        );

        hotels.add(newHotel);

        newHotel = new Hotel__c(
            Name = 'Hotel Test 3', 
            Address__c = 'Testowa 3',
            City__c = 'Testowiron',
            Rating__c = 1
        );

        hotels.add(newHotel);
        insert hotels;
    }
    
    @isTest static void getHotelsTestAll() {
        Test.startTest();

        List<Hotel__c> hotelsTest = HotelDropdownListController.getHotels(2, 'Testowo');

        Test.stopTest();

        System.assertEquals(1, hotelsTest.size());
    }

    @isTest static void getHotelsTestNoRating() {
        Test.startTest();

        List<Hotel__c> hotelsTest = HotelDropdownListController.getHotels(null, 'Testowo');

        Test.stopTest();

        System.assertEquals(2, hotelsTest.size());
    }

    @isTest static void getHotelsTestNoCity() {
     	Test.startTest();

        List<Hotel__c> hotelsTest = HotelDropdownListController.getHotels(2, null);

        Test.stopTest();

        System.assertEquals(1, hotelsTest.size());
    }

    @isTest static void getHotelsTestNothing() {
        Test.startTest();

        List<Hotel__c> hotelsTest = HotelDropdownListController.getHotels(null, null);

        Test.stopTest();

        System.assertEquals(3, hotelsTest.size());
    }
    
    @isTest static void getAllHotelsNull() {
        Test.startTest();

        List<Hotel__c> hotelsTest = HotelDropdownListController.getHotels(5, null);

        Test.stopTest();

        System.assertEquals(null, hotelsTest);
    }
    
    @isTest static void getCityHotelsNull() {
        Test.startTest();

        List<Hotel__c> hotelsTest = HotelDropdownListController.getHotels(null, 'Wrocław');

        Test.stopTest();

        System.assertEquals(null, hotelsTest);
    }
}