objects/Hotel__c.object
<CustomObject>
    <description>Contains a hotel object and its data</description>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address to the hotel containing street name and number. For the city refer to &apos;City&apos; field</description>
        <label>Address</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Contains the city name where hotel is located</description>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Contains an email address of the hotel</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Contact phone for the hotel</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Contains a data about hotel&apos;s rating (1-5 stars)</description>
        <label>Rating</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <description>Contains hotel&apos;s website</description>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/classes/HotelDropdownListController.cls
public with sharing class HotelDropdownListController {
    @AuraEnabled
    public static List<Hotel__c> getHotels() {
        return [SELECT Id, Name 
                FROM Hotel__c];
    }

    @AuraEnabled
    public static Hotel__c getSingleHotel(String id){
        return [SELECT Id, Name, Address__c, City__c, Phone__c, Email__c, Rating__c, Website__c 
                FROM Hotel__c 
                WHERE Id = :id 
                LIMIT 1];
    }
}