objects/Hotel__c.object
<CustomObject>
    <description>Contains a hotel object and its data</description>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address to the hotel containing street name and number. For the city refer to &apos;City&apos; field</description>
        <label>Address</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Contains the city name where hotel is located</description>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Contains an email address of the hotel</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Contact phone for the hotel</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <description>Contains a data about hotel&apos;s rating (1-5 stars)</description>
        <label>Rating</label>
        <precision>1</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <description>Contains hotel&apos;s website</description>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Room__c.object
<CustomObject>
    <description>Contains data about rooms available in hotel</description>
    <fields>
        <fullName>Double_Beds__c</fullName>
        <label>Double Beds</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <description>Refers which hotel owns the room</description>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Maximum_People_in_the_Room__c</fullName>
        <formula>Single_Beds__c  + (2 *  Double_Beds__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Maximum People in the Room</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_for_Night__c</fullName>
        <description>Price PER ONE PERSON</description>
        <label>Price for Night</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Single_Beds__c</fullName>
        <label>Single Beds</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/HotelDropdownListController.cls
public with sharing class HotelDropdownListController {
    @AuraEnabled
    public static List<Hotel__c> getHotels() {
        return [SELECT Id, Name 
                FROM Hotel__c];
    }

    @AuraEnabled
    public static Hotel__c getSingleHotel(String id){
        return [SELECT Id, Name, Address__c, City__c, Phone__c, Email__c, Rating__c, Website__c 
                FROM Hotel__c 
                WHERE Id = :id 
                LIMIT 1];
    }
	

    // @AuraEnabled
    // public static List<Room__c> getRooms(Id id) {
    //     // Perform isAccessible() checking first, then
    //     return [SELECT Name, Single_Beds__c, Double_Beds__c, Price_for_Night__c, Maximum_People_in_the_Room__c
    //             FROM Room__c WHERE Id = :id];
    // }
    
    // @AuraEnabled
    // public static Expense__c saveExpense(Expense__c expense) {
    //     // Perform isUpdateable() checking first, then
    //     upsert expense;
    //     return expense;
    // }
}